/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.oracly.accounts.receivable.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Receivable service. Represents a row in the &quot;Oracly_Receivable&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.oracly.accounts.receivable.model.impl.ReceivableModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.oracly.accounts.receivable.model.impl.ReceivableImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Receivable
 * @see com.liferay.oracly.accounts.receivable.model.impl.ReceivableImpl
 * @see com.liferay.oracly.accounts.receivable.model.impl.ReceivableModelImpl
 * @generated
 */
@ProviderType
public interface ReceivableModel extends BaseModel<Receivable>, GroupedModel,
	ShardedModel, StagedAuditedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a receivable model instance should use the {@link Receivable} interface instead.
	 */

	/**
	 * Returns the primary key of this receivable.
	 *
	 * @return the primary key of this receivable
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this receivable.
	 *
	 * @param primaryKey the primary key of this receivable
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this receivable.
	 *
	 * @return the uuid of this receivable
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this receivable.
	 *
	 * @param uuid the uuid of this receivable
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the foo ID of this receivable.
	 *
	 * @return the foo ID of this receivable
	 */
	public long getFooId();

	/**
	 * Sets the foo ID of this receivable.
	 *
	 * @param fooId the foo ID of this receivable
	 */
	public void setFooId(long fooId);

	/**
	 * Returns the group ID of this receivable.
	 *
	 * @return the group ID of this receivable
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this receivable.
	 *
	 * @param groupId the group ID of this receivable
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this receivable.
	 *
	 * @return the company ID of this receivable
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this receivable.
	 *
	 * @param companyId the company ID of this receivable
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this receivable.
	 *
	 * @return the user ID of this receivable
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this receivable.
	 *
	 * @param userId the user ID of this receivable
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this receivable.
	 *
	 * @return the user uuid of this receivable
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this receivable.
	 *
	 * @param userUuid the user uuid of this receivable
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this receivable.
	 *
	 * @return the user name of this receivable
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this receivable.
	 *
	 * @param userName the user name of this receivable
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this receivable.
	 *
	 * @return the create date of this receivable
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this receivable.
	 *
	 * @param createDate the create date of this receivable
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this receivable.
	 *
	 * @return the modified date of this receivable
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this receivable.
	 *
	 * @param modifiedDate the modified date of this receivable
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the due date of this receivable.
	 *
	 * @return the due date of this receivable
	 */
	public Date getDueDate();

	/**
	 * Sets the due date of this receivable.
	 *
	 * @param dueDate the due date of this receivable
	 */
	public void setDueDate(Date dueDate);

	/**
	 * Returns the amount of this receivable.
	 *
	 * @return the amount of this receivable
	 */
	public Double getAmount();

	/**
	 * Sets the amount of this receivable.
	 *
	 * @param amount the amount of this receivable
	 */
	public void setAmount(Double amount);

	/**
	 * Returns the description of this receivable.
	 *
	 * @return the description of this receivable
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this receivable.
	 *
	 * @param description the description of this receivable
	 */
	public void setDescription(String description);

	/**
	 * Returns the path of this receivable.
	 *
	 * @return the path of this receivable
	 */
	@AutoEscape
	public String getPath();

	/**
	 * Sets the path of this receivable.
	 *
	 * @param path the path of this receivable
	 */
	public void setPath(String path);

	/**
	 * Returns the document ID of this receivable.
	 *
	 * @return the document ID of this receivable
	 */
	public long getDocumentId();

	/**
	 * Sets the document ID of this receivable.
	 *
	 * @param documentId the document ID of this receivable
	 */
	public void setDocumentId(long documentId);

	/**
	 * Returns the flag of this receivable.
	 *
	 * @return the flag of this receivable
	 */
	public int getFlag();

	/**
	 * Sets the flag of this receivable.
	 *
	 * @param flag the flag of this receivable
	 */
	public void setFlag(int flag);

	/**
	 * Returns the supplier name of this receivable.
	 *
	 * @return the supplier name of this receivable
	 */
	@AutoEscape
	public String getSupplierName();

	/**
	 * Sets the supplier name of this receivable.
	 *
	 * @param supplierName the supplier name of this receivable
	 */
	public void setSupplierName(String supplierName);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Receivable receivable);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Receivable> toCacheModel();

	@Override
	public Receivable toEscapedModel();

	@Override
	public Receivable toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}